<a href="https://colab.research.google.com/github/FizaKallatra/Entri-BasicPython/blob/main/AdvancedPythonA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np

In [ ]:
#1. Create a 1D NumPy Array

In [52]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
#2. Inspection and Properties:

In [53]:
print("Shape:", np.shape(temperatures_w1))
print("Size:", np.size(temperatures_w1))
print("Data Type:",type(temperatures_w1))
print("Data Type of elements:",type(temperatures_w1[0]))

Shape: (7,)
Size: 7
Data Type: <class 'numpy.ndarray'>
Data Type of elements: <class 'numpy.float64'>


In [ ]:
#3. Array Operations:

In [54]:
temp_f=temperatures_w1*(9/5)+32
print("Temperature in Fahrenheit:",temp_f)

Temperature in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [55]:
print("Mean temperature of the week:",np.mean(temp_f))
print("Maximum temperature of the week:",np.max(temp_f))
print("Minimum temperature of the week:",np.min(temp_f))

Mean temperature of the week: 74.37714285714286
Maximum temperature of the week: 78.98
Minimum temperature of the week: 69.44


In [ ]:
#4. Array Slicing and Indexing:

In [56]:
print("Temperature for 1st 3 days of the week:",temperatures_w1[:3])
print("Temperature for last 2 days of the week:",temperatures_w1[-2:])
print("Temperature of middle 3 days:",temperatures_w1[2:5])

Temperature for 1st 3 days of the week: [22.5 25.3 20.8]
Temperature for last 2 days of the week: [24.8 21.9]
Temperature of middle 3 days: [20.8 23.4 26.1]


In [57]:
#5. Create a 2D Array:

In [58]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

In [59]:
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [60]:
print("Shape:",np.shape(temperatures))
print("Size:",np.size(temperatures))
print("Data Type:",np.dtype(temperatures[0,1]))


Shape: (2, 7)
Size: 14
Data Type: float64


In [61]:
print("The temperature for week 1:",temperatures[0,:])
print("The temperature for the 1st weekend:",temperatures[0:1,5:7])
print("The temperature for week 2:",temperatures[1,:])
print("The temperature for the 2nd weekend:",temperatures[1:2,5:7])

The temperature for week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
The temperature for the 1st weekend: [[24.8 21.9]]
The temperature for week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
The temperature for the 2nd weekend: [[22.8 20.1]]


In [ ]:
"""Pandas Series:
1. Creating Pandas Series:
"""

In [2]:
import pandas as pd

In [3]:
marks=pd.Series([95,92,89,85,80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [6]:
print("First Rank Student:",marks.loc['Rank1'])

First Rank Student: 95


In [10]:
print("First 3 Rank Student:\n",marks.loc['Rank1':'Rank3'])

First 3 Rank Student:
 Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [11]:
print("Third Rank Student:",marks.iloc[2])

Third Rank Student: 89


In [13]:
high_marks = marks[marks > 90]
print("Ranks with marks > 90:")
print(high_marks)

Ranks with marks > 90:
Rank1    95
Rank2    92
dtype: int64


In [ ]:
#3. Manipulating Series

In [14]:
marks['Rank1']=100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [15]:
marks=marks.drop('Rank5')
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [16]:
cgpa=marks/10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
#Pandas DataFrame

In [17]:
transactions={"TransactionID":[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
              "ProductCategory":['Electronics', 'Clothing', 'Electronics', 'Furniture','Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
              "Region":['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West','South', 'North'],
              "Amount":[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]}

df=pd.DataFrame(transactions)
print(df)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
#2. Data Exploration

In [24]:
print("Shape:",df.shape)
print("Size:",df.size)
print("ColumnName:",df.columns)
print("\nData Type:\n",df.dtypes)
print("\nHead:\n",df.head())
print("\nTail:\n",df.tail())


Shape: (10, 4)
Size: 40
ColumnName: Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

Data Type:
 TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

Head:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail:
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [28]:
print(df[["ProductCategory","Amount"]])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [30]:
print("Last 3 columns:\n",df.iloc[:, -3:])

Last 3 columns:
   ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [33]:
print(df[(df["Region"]=="North") & (df["Amount"]>200)])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [36]:
print(df['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [37]:
print("Unique values in Region:",df["Region"].unique())

Unique values in Region ['North' 'South' 'East' 'West']


In [38]:
print(df.groupby("Region")["Amount"].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [ ]:
#3. Manipulating the DataFrame

In [39]:
df.loc[df["TransactionID"] == 102, "Amount"] = 165
print(df)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [43]:
df["Discount"]=df["Amount"] * 0.10
print(df)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [47]:
df = df[df["TransactionID"] != 109]
print(df)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [50]:
df=df.drop("Discount",axis=1)
print(df)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
